name: 'AWSCredentials Setup'
description: 'Setup or clean aws credentials on build machine.'
inputs:
  iscleanup:
    description: 'Boolean value to indicate if need to create credentials or if this is a cleanup operation.'
    required: true
  awsaccesskeyid:
    description: 'The aws access key Id.'
    required: true
  awsaccesssecret:
    description: 'The aws access secret.'
    required: true        
runs:
  using: 'node20'
  main: 'index.js'